create database clothing;
use clothing;

CREATE TABLE customer_data (
    customer_id INT,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(255),
    category VARCHAR(255),
    purchase_amount INT,
    location VARCHAR(255),
    size VARCHAR(20),
    color VARCHAR(50),
    season VARCHAR(50),
    review_rating FLOAT,
    subscription_status VARCHAR(50),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(20),
    previous_purchases INT,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50),
    age_group VARCHAR(50),
    purchase_frequency_days INT
);

select * from customer_data;
set sql_safe_updates=0;
update customer_data set gender = 'Female' where gender = 'Other';

#total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue 
from customer_data
group by gender;

#which customers used discount but still spent more than average purchase
select customer_id, purchase_amount
from customer_data
where discount_applied = 'Yes'
and purchase_amount >= (
select avg(purchase_amount) from customer_data)
order by purchase_amount desc;


#which are the top 5 products with highest avf review rate
select item_purchased, round(avg(review_rating),2) as 'Average Product Rating'
from customer_data
group by item_purchased
order by avg(review_rating) desc limit 5;


# compare avg purchase amt between standard and express shipping
select shipping_type, round(avg(purchase_amount) ,2)
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type;

#do subscribed customer spend more? compare avg spend and total revenue btwn
#subscribers and non subscribers
select subscription_status,
count(customer_Id) as total_cutomers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_data
group by subscription_status
order by total_revenue, avg_spend desc;

#which 5 products have high percentage of purchase with discount applied
#which product rely heavily on discounts

select item_purchased, 
round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_data group by item_purchased
order by discount_rate desc limit 5;



#segment customers into new,returning nd loyal based on total prev purchase
with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment
from customer_data)

select customer_segment, count(*) as 'Number of customers'
from customer_type 
group by customer_segment;


#top 3 most purchased product 
select item_purchased, count(*) as 'Total Orders' from customer_data
group by item_purchased
order by item_purchased desc limit 3;

#are customers who are repeat buyers do apply subscription?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases>5
group by subscription_status;

#what is the revenue by age group
select age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;




